# Generated by Django 4.0.6 on 2022-08-02 10:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tasktracker', '0002_alter_task_created_at_alter_task_task_assign_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_file',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 2, 15, 46, 59, 144964)),
        ),
    ]
